# Generated by Django 4.0.5 on 2022-06-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.CharField(max_length=200)),
                ('silver', models.CharField(max_length=200)),
                ('bronze', models.CharField(max_length=200)),
            ],
        ),
    ]
